export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_SIGNOUT = 'USER_SIGNOUT'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'
export const USER_SIGNUP_RESET = 'USER_SIGNUP_RESET'

export const MEETING_ADD_REQUEST = "MEETING_ADD_REQUEST"
export const MEETING_ADD_SUCCESS = "MEETING_ADD_SUCCESS"
export const MEETING_ADD_FAIL = "MEETING_ADD_FAIL"
export const MEETING_ADD_RESET = "MEETING_ADD_RESET"

export const LEAVE_FETCH_REQUEST = "LEAVE_FETCH_REQUEST"
export const LEAVE_FETCH_SUCCESS = "LEAVE_FETCH_SUCCESS"
export const LEAVE_FETCH_FAIL = "LEAVE_FETCH_FAIL"
export const LEAVE_FETCH_RESET = "LEAVE_FETCH_RESET"

export const LEAVE_APPROVE_REQUEST = "LEAVE_APPROVE_REQUEST"
export const LEAVE_APPROVE_SUCCESS = "LEAVE_APPROVE_SUCCESS"
export const LEAVE_APPROVE_FAIL = "LEAVE_APPROVE_FAIL"
export const LEAVE_APPROVE_RESET = "LEAVE_APPROVE_RESET"

export const LEAVE_REJECT_REQUEST = "LEAVE_REJECT_REQUEST"
export const LEAVE_REJECT_SUCCESS = "LEAVE_REJECT_SUCCESS"
export const LEAVE_REJECT_FAIL = "LEAVE_REJECT_FAIL"
export const LEAVE_REJECT_RESET = "LEAVE_REJECT_RESET"

export const QUERIES_FETCH_REQUEST = "QUERIES_FETCH_REQUEST"
export const QUERIES_FETCH_SUCCESS = "QUERIES_FETCH_SUCCESS"
export const QUERIES_FETCH_FAIL = "QUERIES_FETCH_FAIL"
export const QUERIES_FETCH_RESET = "QUERIES_FETCH_RESET"

export const QUERIES_STATUS_CHANGE_REQUEST = "QUERIES_STATUS_CHANGE_REQUEST"
export const QUERIES_STATUS_CHANGE_SUCCESS = "QUERIES_STATUS_CHANGE_SUCCESS"
export const QUERIES_STATUS_CHANGE_FAIL = "QUERIES_STATUS_CHANGE_FAIL"
export const QUERIES_STATUS_CHANGE_RESET = "QUERIES_STATUS_CHANGE_RESET"

export const SALARY_SLIP_FETCH_REQUEST = "SALARY_SLIP_FETCH_REQUEST"
export const SALARY_SLIP_FETCH_SUCCESS = "SALARY_SLIP_FETCH_SUCCESS"
export const SALARY_SLIP_FETCH_FAIL = "SALARY_SLIP_FETCH_FAIL"
export const SALARY_SLIP_FETCH_RESET = "SALARY_SLIP_FETCH_RESET"

export const PRESENT_DAY_FETCH_REQUEST = "PRESENT_DAY_FETCH_REQUEST"
export const PRESENT_DAY_FETCH_SUCCESS = "PRESENT_DAY_FETCH_SUCCESS"
export const PRESENT_DAY_FETCH_FAIL = "PRESENT_DAY_FETCH_FAIL"
export const PRESENT_DAY_FETCH_RESET = "PRESENT_DAY_FETCH_RESET"
