export const MEETING_FETCH_REQUEST = 'MEETING_FETCH_REQUEST'
export const MEETING_FETCH_SUCCESS = 'MEETING_FETCH_SUCCESS'
export const MEETING_FETCH_FAIL = 'MEETING_FETCH_FAIL'
export const MEETING_FETCH_RESET = 'MEETING_FETCH_RESET'

export const LEAVE_ADD_REQUEST = 'LEAVE_ADD_REQUEST'
export const LEAVE_ADD_SUCCESS = 'LEAVE_ADD_SUCCESS'
export const LEAVE_ADD_FAIL = 'LEAVE_ADD_FAIL'
export const LEAVE_ADD_RESET = 'LEAVE_ADD_RESET'

export const QUERY_ADD_SUCCESS = "QUERY_ADD_SUCCESS"
export const QUERY_ADD_REQUEST = "QUERY_ADD_REQUEST"
export const QUERY_ADD_FAIL = "QUERY_ADD_FAIL"
export const QUERY_ADD_RESET = "QUERY_ADD_RESET"

export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST'
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL'
export const PROFILE_UPDATE_RESET = 'PROFILE_UPDATE_RESET'

export const PROFILE_FETCH_REQUEST = 'PROFILE_FETCH_REQUEST'
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS'
export const PROFILE_FETCH_FAIL = 'PROFILE_FETCH_FAIL'
export const PROFILE_FETCH_RESET = 'PROFILE_FETCH_RESET'
